spring:
  application:
    name: catalog-service
server:
  port: 9001
  tomcat:
    keep-alive-timeout: 15s
    connection-timeout: 2s
    threads: # for reduced resources consumption at development environment
      max: 50 # max size pool threads can reach
      min-spare: 5 # minimum threads kept running
